/* Copyright (c) 2021 Oracle and/or its affiliates. Contains software licensed under the MIT license. Removal of this notice is prohibited. Full attribution and licensing at: https://ee.channels.ocs.oraclecloud.com/license/license.html */
(function(){var g,h;g=location.protocol+"//static-ph.custhelp.com/s/oit/latest/";h=location.protocol+"//static-ft.custhelp.com/s/oit/latest/";window.inlayLoader=function(a,b,d){var e=window._oitEE.inlayUrl;void 0!==e&&(g=useInlayFullUrl(e)?e:location.protocol+"//"+e+"/s/oit/latest/");var c=document.createElement(b);c.setAttribute("id",b);c.setAttribute("class","inlay");Object.keys(a).forEach(function(b){"div-id"!==b&&c.setAttribute(b,a[b]);"site-type"===b&&"osvc"===a[b]&&(c.setAttribute("ee-data",
JSON.stringify(window._oitEE.eeData)),void 0!==d&&null!==d&&c.setAttribute("_ee-ruleid",d.id));"$siteUrl"==a[b]&&window.siteConfigUrl&&c.setAttribute(b,window.siteConfigUrl)});var f=window._oitEE.inlayCustomData[b]||{};Object.keys(f).forEach(function(a){if("custom-data-type"!==a){var b=window.ATGSvcs.parseJS(f[a]);void 0!==b&&null!==b?c.setAttribute(a,b):console.log(f[a]+" is "+b)}});document.getElementById(a["div-id"])||!0!==_ATGSvcs.CFG["-eeSkylight"]||(b=document.createElement("div"),b.setAttribute("id",
a["div-id"]),document.body.appendChild(b));a["div-id"]&&document.getElementById(a["div-id"]).appendChild(c);a["div-id"]||!0!==_ATGSvcs.CFG["-eeSkylight"]||document.body.appendChild(c);b=function(a,b){var d=function(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.id="oit-loader";useInlayFullUrl(a)?c.src=a:c.src=a+"common/v0/libs/oit/loader.js";c.setAttribute("data-ee-loaded",!0);window._oitEE.oitThemePreset&&c.setAttribute("data-oit-theme",window._oitEE.oitThemePreset);
window._oitEE.dataOitConfigUrl&&c.setAttribute("data-oit-config-url",window._oitEE.dataOitConfigUrl);window._oitEE.dataOitConfigFile&&""!=window._oitEE.dataOitConfigFile&&(dataOitConfigUrlEEManaged=location.protocol+"//"+ATGSvcs.configFileBasePath+"/inlay_config_json/"+window._oitEE.dataOitConfigFile,c.setAttribute("data-oit-config-url",dataOitConfigUrlEEManaged));window._oitEE.dataOitPageId&&c.setAttribute("data-oit-page-id",window._oitEE.dataOitPageId);window._oitEE.dataOitThemeVars&&c.setAttribute("data-oit-theme-vars",
window._oitEE.dataOitThemeVars);null!=b&&(c.onerror=function(){d(b,null)});var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(c,e)};d(a,b)};var k=document.getElementById("oit-loader");k&&!k.getAttribute("data-ee-loaded")&&ATGSvcs.ee.logError({name:"loadererror",message:"Non-EE Implementation of Inlays"},location.href,2,d);void 0!==e?b(g,null):b(g,h)};logInlayMetrics=function(a){if(window.oit&&null!=window.oit&&null!=a.detail){var b=a.detail.inlayId?a.detail.inlayId:a.detail.id,
d=oit.getInlayAttribute(b,"_ee-ruleid"),e;"inlay-oracle-chat-accepted"===a.type?(a=a.detail.source,e="accepted",a="PAC"===a?"oitspchat":"CCL"===a?"oitscchat":"oitemdchat"):(e="offered",a=0<=a.type.indexOf("pac")?"oitspchat":0<=a.type.indexOf("ccl")?"oitscchat":"oitemdchat");window.ATGSvcs.ee.logInvite({id:b,type:a,timestamp:+new Date,state:e,ruleid:d})}};logInlayVsEvent=function(a){if(_vsq&&_vsq._vsEnabled){var b=document.createElement("script");b.setAttribute("type","text/javascript");void 0!=b.addEventListener?
(b.addEventListener("load",function(){_vsq._checkSendSuccess()},!1),b.addEventListener("error",function(){_vsq._handleVSErrors()},!1)):void 0!=b.attachEvent&&b.attachEvent("onreadystatechange",function(){"loaded"==b.readyState&&_vsq._checkSendSuccess()});b.src=_buildInlayVsURI(a);document.getElementsByTagName("head")[0].appendChild(b)}};_buildInlayVsURI=function(a){if(window.oit&&null!=window.oit&&null!=a.detail){var b=a.detail.inlayId?a.detail.inlayId:a.detail.id,d="inlay-oracle-chat-accepted"===
a.type?_vsq.ATYPE.ACCEPT:_vsq.ATYPE.OFFER;a="inlay-oracle-chat-accepted"===a.type?"PAC"===a.detail.source?_vsq.WTYPE.VSSPAC:_vsq.WTYPE.VSSCCL:0<=a.type.indexOf("pac")?_vsq.WTYPE.VSSPAC:_vsq.WTYPE.VSSCCL;var e=oit.getInlayAttribute(b,"site-type"),c=oit.getInlayAttribute(b,"product-id"),f=oit.getInlayAttribute(b,"category-id");if("osvc"==e)return d="//"+_vsq._vip+"/vs/site/"+_vsq._site+"/visitor/"+_oitEE.eeData.v_id+"/session/"+_oitEE.eeData.ee_s_id+"/type/"+d,d=d+("/val1/"+b+"/val2/"+b+"/val3/"+a)+
("?url\x3d"+encodeURIComponent(window.location.href)+"\x26title\x3d"+encodeURIComponent(document.title)),c&&null!=c&&0<=c.length&&(d+="\x26prodId\x3d"+c),f&&null!=f&&0<=f.length&&(d+="\x26categId\x3d"+f),d}};useInlayFullUrl=function(a){return-1<a.indexOf("oit.channels.ocs.oraclecloud.com")||-1<a.indexOf("oit.channels.ocs.oc-test.com")};document.addEventListener("inlay-oracle-chat-embedded-loaded",function(a){window.oit&&null!=window.oit&&null!=a.detail&&"true"!==oit.getInlayAttribute(a.detail.inlayId?
a.detail.inlayId:a.detail.id,"inlay-hidden")&&logInlayMetrics(a)});document.addEventListener("inlay-oracle-chat-ccl-loaded",function(a){logInlayVsEvent(a);logInlayMetrics(a)});document.addEventListener("inlay-oracle-chat-pac-loaded",function(a){logInlayVsEvent(a);logInlayMetrics(a)});document.addEventListener("inlay-oracle-chat-accepted",function(a){"EMBEDDED"!==a.detail.source&&logInlayVsEvent(a);logInlayMetrics(a)});document.dispatchEvent(new CustomEvent("inlayloader-loaded"))})();